import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const interDisplay = localFont({
  src: [
    {
      path: "../public/ttf/InterDisplay-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/ttf/InterDisplay-ThinItalic.ttf",
      weight: "100",
      style: "italic",
    },
    {
      path: "../public/ttf/InterDisplay-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/ttf/InterDisplay-ExtraLightItalic.ttf",
      weight: "200",
      style: "italic",
    },
    {
      path: "../public/ttf/InterDisplay-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/ttf/InterDisplay-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/ttf/InterDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/ttf/InterDisplay-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/ttf/InterDisplay-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/ttf/InterDisplay-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/ttf/InterDisplay-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/ttf/InterDisplay-SemiBoldItalic.ttf",
      weight: "600",
      style: "italic",
    },
    {
      path: "../public/ttf/InterDisplay-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/ttf/InterDisplay-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/ttf/InterDisplay-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/ttf/InterDisplay-ExtraBoldItalic.ttf",
      weight: "800",
      style: "italic",
    },
    {
      path: "../public/ttf/InterDisplay-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/ttf/InterDisplay-BlackItalic.ttf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-inter-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${interDisplay.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
